[tool.poetry]
name = "cfstorm"
version = "0.1.0"
description = ""
authors = ["ray <ray.yu@whu.edu.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sqlalchemy = "^2.0.15"
psycopg2 = "^2.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
